{% set version = "4.6.0" %}

package:
  name: gems3k
  version: {{ version }}

source:
  url: https://github.com/gemshub/GEMS3K/archive/v{{ version }}.tar.gz
  sha256: f93cfc50cd02836bf7a4e86e682e8acfeedf0bd5adeda958297fd366e56b6c75

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [win]
    - make   # [unix]
    - python  # [win or osx]
    - pip  # [win or osx]
    - setuptools  # [win or osx]
    - wheel  # [win or osx]

  host:
    - python
    - pip
    - setuptools
    - wheel
    - pybind11
    - zeromq
    - cppzmq
    - spdlog
    - chemicalfun >=0.1.13
    - thermofun >=0.5.4

  run:
    - python
    - zeromq
    - cppzmq
    - spdlog
    - chemicalfun >=0.1.13
    - thermofun >=0.5.4

test:
  commands:
    - test -d ${PREFIX}/include/GEMS3K  # [unix]
    - test -f ${PREFIX}/include/GEMS3K/node.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GEMS3K\node.h (exit 0) else (exit 1)  # [win]
  imports:
    - solmod4rkt

about:
  home: https://github.com/gemshub/GEMS3K
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Numerical kernel solver of the GEM-Selektor v.3 package for geochemical modelling.
  doc_url: https://github.com/gemshub/GEMS3K
  dev_url: https://github.com/gemshub/GEMS3K

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
